stages:
  - build

.build:
  stage: build
  image: crops/poky
  before_script:
    - export PATH=~/.local/bin:$PATH
    - wget https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - python3 -m pip install kas
    - wget -q 'https://downloads.rclone.org/rclone-current-linux-amd64.zip'
    - unzip -q rclone-current-linux-amd64.zip
    - mv rclone-*-linux-amd64/rclone ~/.local/bin/
    - rm -rf rclone-*-linux-amd64*
  after_script:
    - rm -rf build
  cache:
    paths:
      - layers

odroid-xu3-lite:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-c1:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-c2:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-h2:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-xu4:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-hc1:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-xu3:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME core-image-base

odroid-xu3-lite-x11:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME odroid-x11-image

odroid-h2-x11:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME odroid-x11-image

odroid-xu4-x11:
  extends: .build
  script:
  - ./scripts/ci-build.sh  $CI_JOB_NAME odroid-x11-image
